---
version: 2.1

executors:
  deployer:
    docker:
      - image: cimg/base:2020.12
  php:
    docker:
      - image: cimg/php:8.1.14
        environment:
          - MYSQL_HOST=127.0.0.1
          - DRUSH_SI_DB_URL=mysql://root:@127.0.0.1/testdb
      - image: cimg/mysql:5.7.38

jobs:
  deploy-public-upstream:
    executor: deployer
    steps:
      - checkout
      # Add the ssh key for the pantheon-upstream user. The public ssh key
      # must be added to the CircleCI config, e.g.:
      #   https://app.circleci.com/settings/project/github/pantheon-systems/drupal-composer-managed/ssh
      #
      # Note that this user must have write access both to the source repo,
      # pantheon-systems/drupal-composer-managed (to push the release-pointer
      # tag) and to the target repo, pantheon-upstreams/drupal-composer-managed.
      #
      # Read the ssh keypair from vault:
      #   pvault production read secret/securenotes/pantheon-upstream_github_ssh_key
      # Or generate a new one via:
      #   ssh-keygen -m PEM -t rsa -C "your_email@example.com"
      # Also add the private key to the Github user, e.g.:
      #   https://github.com/settings/keys
      # Credentials to log in as the pantheon-upstream user are available in vault:
      #   pvault production read secret/securenotes/github_user__pantheon-upstream
      # You may confirm the fingerprint via:
      #   ssh-keygen -l -E md5 -f ed25519
      - add_ssh_keys:
          fingerprints:
            - "50:72:cc:79:5d:fa:9d:b9:83:40:af:e9:4a:37:4f:4b"
      - run:
          name: Copy commits to destination repo
          command: devops/scripts/deploy-public-upstream.sh
  deploy-decoupled-upstream:
    executor: deployer
    steps:
      - checkout
      # Add the ssh key for the pantheon-upstream user. The public ssh key
      # must be added to the CircleCI config, e.g.:
      #   https://app.circleci.com/settings/project/github/pantheon-systems/drupal-composer-managed/ssh
      #
      # Note that this user must have write access both to the source repo,
      # pantheon-systems/drupal-composer-managed (to push the release-pointer
      # tag) and to the target repo, pantheon-upstreams/drupal-composer-managed.
      #
      # Read the ssh keypair from vault:
      #   pvault production read secret/securenotes/pantheon-upstream_github_ssh_key
      # Or generate a new one via:
      #   ssh-keygen -m PEM -t rsa -C "your_email@example.com"
      # Also add the private key to the Github user, e.g.:
      #   https://github.com/settings/keys
      # Credentials to log in as the pantheon-upstream user are available in vault:
      #   pvault production read secret/securenotes/github_user__pantheon-upstream
      # You may confirm the fingerprint via:
      #   ssh-keygen -l -E md5 -f ed25519
      - add_ssh_keys:
          fingerprints:
            - "50:72:cc:79:5d:fa:9d:b9:83:40:af:e9:4a:37:4f:4b"
      - run:
          name: Run decoupledpatch.sh and copy commits to decoupled destination repo
          command: devops/scripts/deploy-decoupled-upstream.sh
  unit-test:
    executor: php
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
              cd devops/phpunit
              composer install
              composer unit
  check-commits:
    executor: deployer
    steps:
      - checkout
      - run:
          name: Check validity of commits in PR
          command: devops/scripts/check-commits.sh
  check-patch:
    executor: deployer
    steps:
      - checkout
      - run:
          name: Check that patch file applies without errors
          command: devops/scripts/check-patch.sh

workflows:
  version: 2
  deploy-public-upstream:
    jobs:
      - deploy-public-upstream:
          filters:
            branches:
              only:
                - release
      - deploy-decoupled-upstream:
          filters:
            branches:
              only:
                - release
  check:
    jobs:
      - unit-test
      - check-commits:
          requires:
            - unit-test
      - check-patch:
          requires:
            - unit-test
